### ISSUE TITLE
Support for Latest Dependencies: Compatibility with @ckeditor/ckeditor5-vue version 7.2.0 for Vue.js

### ISSUE THREAD

**Issue by ziadbastawy** [rickx81/ckeditor5-line-height#2]
Hello,

I am currently using version 43.0.0 of this package in my Vue.js project, but I encounter the following error when trying to use it with @ckeditor/ckeditor5-vue version 7.2.0:

> **"CKEditorError: ckeditor-duplicated-modules"**

This error seems to occur due to a mismatch in versions or duplicated modules between the current package version and CKEditor's latest version.

I kindly request support for @ckeditor/ckeditor5-vue version 7.2.0, allowing the package to be compatible with the latest CKEditor integration. This would help avoid the module duplication error and ensure compatibility with new features and fixes provided by CKEditor.

Thank you for your attention to this, and I look forward to the update!

**Comment by ziadbastawy** [comment]
I also tried to downgrade to package to support latest supported version but got same error here is packages.json : 

    "@ckeditor/ckeditor5-adapter-ckfinder": "^42.0.1",
    "@ckeditor/ckeditor5-alignment": "^42.0.1",
    "@ckeditor/ckeditor5-basic-styles": "^42.0.1",
    "@ckeditor/ckeditor5-build-classic": "^42.0.1",
    "@ckeditor/ckeditor5-clipboard": "^42.0.1",
    "@ckeditor/ckeditor5-easy-image": "^42.0.1",
    "@ckeditor/ckeditor5-essentials": "^42.0.1",
    "@ckeditor/ckeditor5-font": "^42.0.1",
    "@ckeditor/ckeditor5-heading": "^42.0.1",
    "@ckeditor/ckeditor5-html-support": "^42.0.1",
    "@ckeditor/ckeditor5-image": "^42.0.1",
    "@ckeditor/ckeditor5-link": "^42.0.1",
    "@ckeditor/ckeditor5-list": "^42.0.1",
    "@ckeditor/ckeditor5-paragraph": "^42.0.1",
    "@ckeditor/ckeditor5-source-editing": "^42.0.1",
    "@ckeditor/ckeditor5-table": "^42.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^42.0.1",
    "@ckeditor/ckeditor5-upload": "^42.0.1",
    "@rickx/ckeditor5-line-height": "^42.0.1",
    "@ckeditor/ckeditor5-vue": "^6.0.0"

**Comment by rickx81** [comment]
try update ckeditor5 >= 42.0.0
[Update to CKEditor 5 v42.x](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-42.html)
[Migrating from customized builds](https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/customized-builds.html)

and it's an example [stackblitz](https://stackblitz.com/edit/vitejs-vite-kpsxns?file=src%2Fcomponents%2FHelloWorld.vue)

**Comment by ziadbastawy** [comment]
it worked fine thanks for your support
